/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wRUXSo9hJ2t
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "../ui/button";

export function ItemCard() {
  return (
    <Card className="w-full max-w-xs">
      <CardContent className="flex aspect-square items-center justify-center p-3">
        <img
          src="/placeholder.svg"
          width="400"
          height="400"
          alt="Product image"
          className="aspect-square object-cover rounded-lg overflow-hidden"
        />
      </CardContent>
      <CardHeader className="text-center">
        <CardTitle>Classic sunglasses</CardTitle>
      </CardHeader>
      <CardContent className="text-3xl font-semibold flex items-center justify-center">
        <CardContent className="text-3xl font-semibold flex items-center justify-center pb-0">
          $49
        </CardContent>
      </CardContent>
      <CardContent className="font-semibold flex items-center justify-center gap-2">
        <Button className="bg-slate-800">Add to cart</Button>
        <Button className="bg-slate-800">Rent</Button>
      </CardContent>
    </Card>
  );
}
