/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wRUXSo9hJ2t
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"

export function ItemCard() {
  return (
    (<Card className="w-full max-w-sm mx-auto">
      <CardContent className="flex aspect-square items-center justify-center p-6">
        <img
          src="/placeholder.svg"
          width="400"
          height="400"
          alt="Product image"
          className="aspect-square object-cover rounded-lg overflow-hidden" />
      </CardContent>
      <CardHeader className="text-center">
        <CardTitle>Classic sunglasses</CardTitle>
        <CardDescription>UV-400 protection</CardDescription>
      </CardHeader>
      <CardContent className="text-3xl font-semibold flex items-center justify-center">$49</CardContent>
    </Card>)
  );
}
